language: node_js
sudo: false
node_js:
- 9
- 8
- 6
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
after_success:
- npm run build
before_deploy:
- ls
deploy:
  provider: npm
  skip_cleanup: true
  email: leonard@marschke.me
  on:
    tags: true
  api_key:
    secure: nNQHRpEmd5HF0wlpJOYS7kFq/u5/AAQFSJ37aW7i9wT12GLRLoTfSqVQxWocSguJU7Gl7kcQirxmXFrGIzM+b+JMpQZeI+p0oXG/zf1R8KTUr92zreGMyQ1oMbsfdnLDRW5ZBcp1tQZSc6L7MVjdI2urEmfGKIlqKdbLUyH+5gpZm0/CfwdKRoUeEqmSPhiqCvCvF/Xx439+T/fRsgYWGLk/rudcyMme3JLrhQgR/+diYMBEFPRnT7xL7v3sMEQC9Pyo17urzzBSjKsmO12fAPl5WrIz5mjW8tFZ6u8vcgF9eONYwsbd1fiUI7mpVkCrcLI0vBoRqgOEOSNi2WQe7SJScjPRWHlBE/URCLu1YFXfEJsRWlOtMBht6MZreZn9w0WV3gJ4DFrpxy9+hRFYSdy86qpb0piezkazf/nqAxPZ9yR5hjJz1Gt1415qKXfdqKpXxP2rlnXoQms6jNilxTUTC3aXlR18C8gi3PZ6e7Dz8hFaCAQiuWO8i41M9e5aA8iajq48PxWTkEssZ5rgCN21lzdKZerV9ECiWTeIxl4M4uXF++M85vUyHRMWWLalEh1VjGtdT65WqWnhxiqxacIjLhrc3gSccMHHz6Kq+XLS2sZs6GEVfpTDqxKOOshF+nb6F5HhSQl1CQVG8ksGu2IURhZQwRi/bFcQzaPAw3Q=
