language: node_js
sudo: false
node_js:
- 9
- 8
- 6
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
after_success:
  - npm run build
before_deploy:
  - cd dist
  - cp ../package.json .
deploy:
  provider: npm
  skip_cleanup: true
  email: leonard@marschke.me
  on:
    tags: true
  api_key:
    secure: ET4f5cBcddnNBVD2XYoVmk0xAw4lmPa/yLwN4p7p8whIAtz5y8V82GghCs1ZIHm127dxb8cmcKRJXuCXgH2P0GrnDA+jmDrWg7SgtMSMpAnAh3bka/AQIXpwE27nzI9UlzRWzsbhmQ0SaiVRsc6QzBB+1uCHZkdGk5+3ietw4LSdeDlUsCCUU2W+OcS8njEOP5w9f40xade5dF8gfSPvm7FL9UDQkyY+nE1qtu/56XuyRgp7tdJJ20pEXkh8ZQqRjPzS/0eijKlfJ9tHcVvm2GP175RHnBgM2FqFqqmJjenlDxgZM/gd+Taaqshvr+eu1aY8fkF732fYtUq+DCawp51PSMorw6DjKJfI92KAEsV2DFBZOn7VdxaO3OdrsCXtZU+rLZOAH3k8Si2aOeN8j20Szm+Q09j4MIGdilPTiP+Wu8M8WxonOOkSdvukj5vFXcCjsjCrMeafTnRYV4fRGbHL0eUbhW7e2BsSmm7UVOWzUkQ3NioQsReHIXgaKcxrBBpqvPwnx9X5KHaNoI5ofJDHAonFXXrVFFn2DFb9Sa+jjgmMhF5nz73idvlLrCazdSiHy4W8CBetrxmUEJmu640k9uHJ74s64COgM7H9X2UUtExcUFvb234qIgWBt//NsYfHqndNs9+ezfzzGGnyTGXHeIPNECU/TER72o4b0n4=
